#!/usr/bin/env bash

# Alias
alias v="nvim"
alias ls="eza --color=always --color-scale-mode=gradient --icons=auto -a"
alias c="clear"
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout'
alias python='python3'

