#!/usr/in/env bash
:q



# refresh new .tumx.conf
rm -f $HOME/.tmux.conf
cp ./tmux/.tmux.conf $HOME/

# Delete the existing tpm repo if exist and install tmp 
rm -rf ~/.tmux/plugins/tpm
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# Install dependencies
brew install --cask font-monaspace-nerd-font font-noto-sans-symbols-2
brew install bash bc coreutils gawk gh glab gsed jq nowplaying-cli
